name: Build-Plugin

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Toolchain
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache UE binaries
        uses: actions/cache@v4
        with:
          path: 'C:/Program Files/Epic Games/UE_5.4'
          key: UE5.4-win64

      - name: Build plugin
        run: |
          & "C:/Program Files/Epic Games/UE_5.4/Engine/Build/BatchFiles/RunUAT.bat" BuildPlugin ^
            -Plugin="${{ github.workspace }}/Plugins/SquadAI/SquadAI.uplugin" ^
            -Package="${{ github.workspace }}/PluginPackages/SquadAI" ^
            -TargetPlatforms=Win64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SquadAI-win64
          path: PluginPackages/SquadAI
