name: Build-Plugin

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-2022, ubuntu-22.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Toolchain
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache UE binaries
        uses: actions/cache@v4
        with:
          path: ${{ runner.os == 'Windows' && 'C:/Program Files/Epic Games/UE_5.4' || '/opt/UE_5.4' }}
          key: UE5.4-${{ runner.os }}

      - name: Build plugin
        run: |
          ${{ runner.os == 'Windows' && '& "C:/Program Files/Epic Games/UE_5.4/Engine/Build/BatchFiles/RunUAT.bat"' || '/opt/UE_5.4/Engine/Build/BatchFiles/RunUAT.sh' }} BuildPlugin \
            -Plugin="${{ github.workspace }}/Plugins/SquadAI/SquadAI.uplugin" \
            -Package="${{ github.workspace }}/PluginPackages/SquadAI-${{ runner.os }}" \
            -TargetPlatforms=${{ runner.os == 'Windows' && 'Win64' || 'Linux' }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SquadAI-${{ runner.os }}
          path: PluginPackages/SquadAI-${{ runner.os }}
